### ISSUE TITLE
System.ArgumentException on start

### ISSUE THREAD

**Issue by mgraszek** [PyriteServer/PyriteCli#30]
Hello

I'm checking the PyriteCli from the tutorial how it should be used.
Unfortunatelly it fails for me when i try to slice the sample obj.

pyritecli -x 12 -u 6 -v 6 -p -c -t d:\pyrite\sample\model.jpg d:\pyrite\output\L1 d:\pyrite\sample\model_high.obj

This and other commands fails on -X variable.

> Due to -ForceCubical grid size is now 12,12,12
> PyriteCli Information: 0 : Loading d:\projects\Pyro3d\model\model_high.obj
> 
> Wyjątek nieobsłużony: System.ArgumentException: Could not parse X parameter as d
> ouble

Could anyone explain whats going on?
I receive same problem on both release versions.

**Comment by stefangordon** [comment]
I wonder if perhaps copy/pasting the command line from the browser might have put bad characters in that could not be parsed? You might try typing instead if you pasted?  I will also test this later tonight and get back to you, entirely possible we have broken something.

**Comment by stefangordon** [comment]
Oh, I spoke too soon - I see this failure is in parsing the vertices in the OBJ.  If I had to guess it is a locale problem on parsing floats, and you may be the first person to test outside of en-us.   I'll get this verified and fixed today and get back to you,.

**Comment by mgraszek** [comment]
Thanks for sooooo fast answer.
I didn't expect that ;)

**Comment by stefangordon** [comment]
I quickly updated the `double.tryparse` calls to include an invariant culture parameter but I haven't put in any way to run our unit tests in another culture yet so I can't be sure if this will fix all the issues or not.

Release binaries built after the commit referenced above are here:
[PyriteCLI_v1-alpha.2.1_x64.zip](https://github.com/PyriteServer/PyriteCli/files/887017/PyriteCLI_v1-alpha.2.1_x64.zip)

Given the lack of documentation for more advanced features at the moment you should feel free to post any questions about your scenario and I can get you going in the right direction.

**Comment by mgraszek** [comment]
Okay. I was able to turn everything on. 
Your version seems to work. Please add it to release page.

I have other question, but i will create other issue for that.
